### ISSUE TITLE
[TODO] Launch Dev environment with testnet

### ISSUE THREAD

**Issue by JonathonDunford** [Agorex-io/Cooperative#11]
- [ ] Design new logo (optional)
- [x] Add ability to function on Rinkeby network - BACKEND
- [ ] Merge @activescott 's 2 changes to front end: https://github.com/Agorex-io/FrontEnd/issues/29 , https://github.com/Agorex-io/FrontEnd/issues/16
- [ ] Add ability to function on Rinkeby network - FRONTEND
- [ ] Deploy parity node of Rinkeby network
- [ ] Deploy current version of contract onto Rinkeby network and point both backend & frontend configs to it
- [ ] Deploy backend onto a server
- [ ] Launch dev version on either GitHub pages or dev.agorex.io

**Comment by JonathonDunford** [comment]
> Add ability to function on Rinkeby network - BACKEND

Closed with: https://github.com/Agorex-io/BackEnd/pull/42
