### ISSUE TITLE
[TODO] Master List

### ISSUE THREAD

**Issue by JonathonDunford** [Agorex-io/Cooperative#4]
There are a million and fifteen things we need to do to get this project properly launched, so I thought that organizing those items into a singular, master todo list would help until we get a better process in place (maybe using a tool like Freedcamp).

If you identify an item on this list that you would like to work on, is in a PR, or is in another issue, please let me know and I will edit this original comment to reflect that information.

This document will be updated regularly, so it is a good place to get up to date information on the status of multiple aspects of the project.

The main point of this document is to get a public list of items we need help completing, so that members/contributors understand areas they can help in. If you would like to help in any of the areas below, please drop a comment below.

Also, I am sure this list is far from complete. If you can think of other items that should belong on this list, drop a comment below as well.

# Master Todo List

## Structural
- [ ] Finalize "AIP-1" (issue https://github.com/Agorex-io/Proposals/issues/1 in proposals)
- [ ] Set up legal entity (AIP-2)
- [x] Legal Counsel
- [ ] CPA (Tax) counsel
- [ ] About Page explaining the Coop & DEX
- [ ] Quickstart Guide on Joining coop & contributing
- [ ] Membership Code of Conduct
- [ ] Contribution Guidelines
- [ ] Develop voting procedure (is it based on a DAO, or some simpler system?)

## Business
- [ ] Research Funding Options
- [ ] Research Strategic Partnerships
- [x] Explore different revenue generation models
- [ ] Compile revenue generation options into proposals

## Design
- [ ] Logo design options + branding (colors, fonts, etc.)
- [ ] New UI/UX design

### New UI
- [x] Create a list of all of the features that should be included with the new UI
- [ ] New charting section (features / layout)
- [ ] New order book design
- [ ] New buy/sell design
- [ ] New transaction history that actually stores trades
- [ ] New "My Funds" section that shows ALL of the users funds on the smart contract
- [ ] New "My Orders" section that shows ALL of the users open orders
- [ ] When users are depositing ETH/tokens that will allow an existing order to execute, warn user
- [ ] Improve all of the error messages to give clear instructions on how to fix
- [ ] Ability to select Ledger accounts
- [ ] Trezor support
- [ ] Reasonable max expiry dates on orders (enforce this in backend)
- [ ] Token listings URLs based on name, not ticker
- [ ] Filterable token dropdown list that searches on ticker / name
- [ ] Allow users to add custom tokens to their own interface
- [ ] Fix bugs with Ledger transactions and 1 gas price
- [ ] Warn user when opening direct contract link
- [ ] Add support for token logos
- [ ] Auto checkbox option for gas prices fetched from ethgasstation.info
- [ ] Detect hung metamask
- [ ] Walkthrough for new users (cookie based) that explains how to use the exchange
- [ ] Ability to "favorite" tokens so they show up first in the list

### Backend
- [ ] Complete this milestone: https://github.com/Agorex-io/BackEnd/milestone/1

_* multiple items inside milestone_

### Smart Contract
- [ ] Create a pros and cons list of using 0x versus our self made contract.
- [ ] Finish a smart contract migration tool (look into other contract migrations we should support outside of etherdelta's contract?)
- [ ] Explore a market orders solution
- [ ] Audit

## Marketing
- [ ] Jonathon: I would personally hold off on marketing until we launch beta or we could get overwhelmed. What do you all think?

## Community Management
_This will be more prevalent when we develop a marketing strategy._
- [ ] We should have community managers / support staff available 24/7. This may mean we need to find people in all different time zones.

## Tokens
- [ ] Formalize listing requirements + procedure
- [ ] Formalize delisting procedure
- [ ] Go through Delisting requests (issues) and make one giant Pull request
- [ ] Go through listing requests
- [ ] Finishing going through tokens list to delist "bad" tokens
- [ ] Go through competitor's tokens and list any that we may have missed

**Comment by rowmagnon** [comment]
Getting ahead here but:
Implement CSS stylesheet for subreddit (use final UI + logo as reference)

**Comment by Simon0x** [comment]
Better support of hardware wallets. For example, the selection of accounts from the ledger and not just the first account.
That's something that's always bothered me.

**Comment by FinanceRebellion** [comment]
Building of an in depth help desk, including articles with examples and explanations. We want new customers to have a first point of assistance when they have basic questions.

**Comment by Rally-Arceno** [comment]
I've seen on https://token.store the adding of custom token is reading the symbol, name and decimal directly from the contract. The user only provides the address. Could this be an enhancement for usability?

**Comment by Rally-Arceno** [comment]
Also some are scared to use DEX for not being good on usability and find it complex. On https://rektex.github.io , they added 'Help' menu with different videos steps on how to use the exchange. I find this comforting if I am a new user, rather that going back and forth in reddit with an issue as if there is a problem on the exchange.
